release:
  prerelease: auto
  draft: false

env:
  # required to support multi architecture docker builds
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - CGO_ENABLED=0

builds:
  - id: linux-build
    dir: ./
    binary: gorevproxy
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    # set the modified timestamp on the output binary to the git timestamp to ensure a reproducible build
    mod_timestamp: &build-timestamp '{{ .CommitTimestamp }}'
    ldflags: &build-ldflags |
      -w
      -s
      -extldflags '-static'

  - id: darwin-build
    dir: ./
    binary: gorevproxy
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: *build-timestamp
    ldflags: *build-ldflags

  - id: windows-build
    dir: ./
    binary: gorevproxy
    goos:
      - windows
    goarch:
      - amd64
    mod_timestamp: *build-timestamp
    ldflags: *build-ldflags

archives:
  - id: linux-archives
    builds:
      - linux-build

  - id: darwin-archives
    builds:
      - darwin-build

  - id: windows-archives
    format: zip
    builds:
      - windows-build

dockers:
  - image_templates:
      # - shanedell/gorevproxy:latest
      # - shanedell/gorevproxy:{{.Tag}}
      - ghcr.io/shanedell/gorevproxy:latest
      - ghcr.io/shanedell/gorevproxy:{{.Tag}}
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

  - image_templates:
      # - shanedell/gorevproxy:{{.Tag}}-arm64
      - ghcr.io/shanedell/gorevproxy:{{.Tag}}-arm64
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--build-arg=BUILD_DATE={{.Date}}"
      - "--build-arg=BUILD_VERSION={{.Version}}"
      - "--build-arg=VCS_REF={{.FullCommit}}"
      - "--build-arg=VCS_URL={{.GitURL}}"

docker_manifests:
  # - name_template: shanedell/gorevproxy:latest
  #   image_templates:
  #     - shanedell/gorevproxy:{{.Tag}}
  #     - shanedell/gorevproxy:{{.Tag}}-arm64

  # - name_template: shanedell/gorevproxy:{{.Tag}}
  #   image_templates:
  #     - shanedell/gorevproxy:{{.Tag}}
  #     - shanedell/gorevproxy:{{.Tag}}-arm64

  - name_template: ghcr.io/shanedell/gorevproxy:latest
    image_templates:
      - ghcr.io/shanedell/gorevproxy:{{.Tag}}
      - ghcr.io/shanedell/gorevproxy:{{.Tag}}-arm64

  - name_template: ghcr.io/shanedell/gorevproxy:{{.Tag}}
    image_templates:
      - ghcr.io/shanedell/gorevproxy:{{.Tag}}
      - ghcr.io/shanedell/gorevproxy:{{.Tag}}-arm64
